const { PLATFORM } = require('aurelia-pal');

module.exports = [
  {
    route: "account-bank",
    name: "account-bank",
    moduleId: PLATFORM.moduleName('./modules/master/account-bank/index', 'master'),
    nav: true,
    title: "Akun Bank",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B4: 1, B1: 1, B12: 1 },
      permission :{"B1":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "bi-currency",
    name: "bi-currency",
    moduleId: PLATFORM.moduleName('./modules/master/bi-currency/index', 'master'),
    nav: true,
    title: "Kurs BI",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B11: 1, B1: 1, B12: 1 },
      permission :{"B2":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "buyers",
    name: "buyers",
    moduleId: PLATFORM.moduleName('./modules/master/buyer/index', 'master'),
    nav: true,
    title: "Buyer",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A2: 1 },
      permission :{"B3":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "suppliers/budgeting",
    name: "suppliers/budgeting",
    moduleId: PLATFORM.moduleName('./modules/master/supplier-budgeting/index', 'master'),
    nav: true,
    title: "Supplier",
    auth: true,
    settings: {
      group: "master",
      // permission: { C5: 1, C9: 1, P1: 7, P3: 7, P4: 7, P6: 7, P7: 7, PG: 7 },
      permission :{"B4":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "suppliers",
    name: "suppliers",
    moduleId: PLATFORM.moduleName('./modules/master/supplier/index', 'master'),
    nav: true,
    title: "Supplier (All User)",
    auth: true,
    settings: {
      group: "master",
      // permission: { P1: 1, P3: 1, P4: 1, P6: 1, P7: 1, PG: 1 },
      permission :{"B5":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "uoms",
    name: "uoms",
    moduleId: PLATFORM.moduleName('./modules/master/uom/index', 'master'),
    nav: true,
    title: "Satuan",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 },
      permission :{"B6":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-categories",
    name: "garment-categories",
    moduleId: PLATFORM.moduleName('./modules/master/garment-category-budgeting/index', 'master'),
    nav: true,
    title: "Kategori Garment",
    auth: true,
    settings: {
      group: "master",
      //permission: { "P1": 1, "P3": 1, "P4": 1, "P6": 1, "P7": 1, "S4": 1, "C3": 1, "E": 1, "K": 1, "S1": 1, "S2": 1, "S3": 1, "U1": 1, "F1": 1, "F2": 1, "L3": 1, "LK": 1, "L8": 1, "L2": 1, "C2": 1, "A2": 1, "C1": 1, "B5": 1, "L1": 1, "B4": 1, "B3": 1, "C4": 1, "OJ": 1, "A1": 1, "B9": 1, "A4": 1, "P1A": 1, "C2A": 1, "C2B": 1, "FP": 1, "PI": 1, "P": 1, "FC": 1, "GU": 1, "GS": 1, "PG": 1, "C1A": 1, "C1B": 1, "KK": 1, "B1": 1 },
      // permission: { "C9": 1, "PGA": 1 },
      permission :{"B7":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-products/budgeting",
    name: "garment-products/budgeting",
    moduleId: PLATFORM.moduleName('./modules/master/garment-product-budgeting/index', 'master'),
    nav: true,
    title: "Barang Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { C5: 1, C9: 1 },
      permission :{"B8":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-products",
    name: "garment-products",
    moduleId: PLATFORM.moduleName('./modules/master/garment-product/index', 'master'),
    nav: true,
    title: "Barang Garment (All User)",
    auth: true,
    settings: {
      group: "master",
      // permission: {
      //   PGA: 1,
      //   P1: 1,
      //   P3: 1,
      //   P4: 1,
      //   P6: 1,
      //   P7: 1,
      //   S4: 1,
      //   C3: 1,
      //   E: 1,
      //   K: 1,
      //   S1: 1,
      //   S2: 1,
      //   S3: 1,
      //   U1: 1,
      //   F1: 1,
      //   F2: 1,
      //   L3: 1,
      //   LK: 1,
      //   L8: 1,
      //   L2: 1,
      //   C2: 1,
      //   A2: 1,
      //   C1: 1,
      //   B5: 1,
      //   L1: 1,
      //   B4: 1,
      //   B3: 1,
      //   C4: 1,
      //   OJ: 1,
      //   A1: 1,
      //   B9: 1,
      //   A4: 1,
      //   P1A: 1,
      //   C2A: 1,
      //   C2B: 1,
      //   FP: 1,
      //   PI: 1,
      //   P: 1,
      //   FC: 1,
      //   GU: 1,
      //   GS: 1,
      //   PG: 1,
      //   C1A: 1,
      //   C1B: 1,
      //   KK: 1,
      //   B1: 1,
      // },
      permission :{"B9":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: 'garment-section',
    name: 'garment-section',
    moduleId: PLATFORM.moduleName('./modules/master/garment-section/index', 'master'),
    nav: true,
    title: 'Master Seksi',
    auth: true,
    settings: {
        group: "master",
        // permission: { "PGA": 1, "C9": 1 },
        permission :{"B10":1},
        iconClass: 'fa fa-dashboard',
     },
  },
  {
    route: "master/garment-marketing",
    name: "garment-marketing",
    moduleId: "modules/master/garment-marketing/index",
    nav: true,
    title: "Marketing Garment",
    auth: true,
    settings: {
        group: "master",
        // permission: { "PGA": 1, "C9": 1 },
        permission :{"B58":1},
        iconClass: "fa fa-dashboard"
       }
  },
  {
    route: "garment-buyers",
    name: "garment-buyers",
    moduleId: PLATFORM.moduleName('./modules/master/garment-buyer/index', 'master'),
    nav: true,
    title: "Buyer Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A2: 1,SG:1 },
      permission :{"B11":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-buyers-list",
    name: "garment-buyers-list",
    moduleId: PLATFORM.moduleName('./modules/master/garment-buyer-list/index', 'master'),
    nav: true,
    title: "List Buyer Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, PGA: 1 ,SG:1},
      permission :{"B12":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-buyer-brands",
    name: "garment-buyer-brands",
    moduleId: PLATFORM.moduleName('./modules/master/garment-buyer-brand/index', 'master'),
    nav: true,
    title: "Brand Buyer Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A2: 1 ,SG:1},
      permission :{"B13":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-buyer-brands-list",
    name: "garment-buyer-brands-list",
    moduleId: PLATFORM.moduleName('./modules/master/garment-buyer-brand-list/index', 'master'),
    nav: true,
    title: "List Brand Buyer Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, PGA: 1 ,SG:1},
      permission :{"B14":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-omzet-target",
    name: "garment-omzet-target",
    moduleId: PLATFORM.moduleName('./modules/merchandiser/garment-omzet-target/index', 'master'),
    nav: true,
    title: "Target Omzet Divisi Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { PGA: 1, C5: 1, C9: 1 },
      permission :{"B15":1},
      iconClass: "fa fa-dashboard",
    },
  },
  // {
  //   route: "garment-categories",
  //   name: "garment-categories",
  //   moduleId: PLATFORM.moduleName('./modules/master/garment-category/index', 'master'),
  //   nav: true,
  //   title: "Kategori Garment",
  //   auth: true,
  //   settings: {
  //     group: "master",
  //     //permission: { "P1": 1, "P3": 1, "P4": 1, "P6": 1, "P7": 1, "S4": 1, "C3": 1, "E": 1, "K": 1, "S1": 1, "S2": 1, "S3": 1, "U1": 1, "F1": 1, "F2": 1, "L3": 1, "LK": 1, "L8": 1, "L2": 1, "C2": 1, "A2": 1, "C1": 1, "B5": 1, "L1": 1, "B4": 1, "B3": 1, "C4": 1, "OJ": 1, "A1": 1, "B9": 1, "A4": 1, "P1A": 1, "C2A": 1, "C2B": 1, "FP": 1, "PI": 1, "P": 1, "FC": 1, "GU": 1, "GS": 1, "PG": 1, "C1A": 1, "C1B": 1, "KK": 1, "B1": 1 },
  //     iconClass: "fa fa-dashboard",
  //   },
  // },
  {
    route: "garment-suppliers/budgeting",
    name: "garment-suppliers/budgeting",
    moduleId: PLATFORM.moduleName('./modules/master/garment-supplier-budgeting/index', 'master'),
    nav: true,
    title: "Supplier Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { APG: 1, C9: 1 },
      permission :{"B16":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "garment-suppliers",
    name: "garment-suppliers",
    moduleId: PLATFORM.moduleName('./modules/master/garment-supplier/index', 'master'),
    nav: true,
    title: "Supplier Garment (All User)",
    auth: true,
    settings: {
      group: "master",
      // permission: {
      //   P1: 1,
      //   P3: 1,
      //   P4: 1,
      //   P6: 1,
      //   P7: 1,
      //   S4: 1,
      //   C3: 1,
      //   E: 1,
      //   K: 1,
      //   S1: 1,
      //   S2: 1,
      //   S3: 1,
      //   U1: 1,
      //   F1: 1,
      //   F2: 1,
      //   L3: 1,
      //   LK: 1,
      //   L8: 1,
      //   L2: 1,
      //   C2: 1,
      //   A2: 1,
      //   C1: 1,
      //   B5: 1,
      //   L1: 1,
      //   B4: 1,
      //   B3: 1,
      //   C4: 1,
      //   OJ: 1,
      //   A1: 1,
      //   B9: 1,
      //   A4: 1,
      //   P1A: 1,
      //   C2A: 1,
      //   C2B: 1,
      //   FP: 1,
      //   PI: 1,
      //   P: 1,
      //   FC: 1,
      //   GU: 1,
      //   GS: 1,
      //   PG: 1,
      //   C1A: 1,
      //   C1B: 1,
      //   KK: 1,
      //   B1: 1,
      // },
      permission :{"B17":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "products/budgeting",
    name: "products/budgeting",
    moduleId: PLATFORM.moduleName('./modules/master/product-budgeting/index', 'master'),
    nav: true,
    title: "Barang",
    auth: true,
    settings: {
      group: "master",
      // permission: { C5: 1, C9: 1 },
      permission :{"B18":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "products",
    name: "products",
    moduleId: PLATFORM.moduleName('./modules/master/product/index', 'master'),
    nav: true,
    title: "Barang (All User)",
    auth: true,
    settings: {
      group: "master",
      // permission: {
      //   P1: 1,
      //   P3: 1,
      //   P4: 1,
      //   P6: 1,
      //   P7: 1,
      //   S4: 1,
      //   C3: 1,
      //   E: 1,
      //   K: 1,
      //   S1: 1,
      //   S2: 1,
      //   S3: 1,
      //   U1: 1,
      //   F1: 1,
      //   F2: 1,
      //   L3: 1,
      //   LK: 1,
      //   L8: 1,
      //   L2: 1,
      //   C2: 1,
      //   A2: 1,
      //   C1: 1,
      //   B5: 1,
      //   L1: 1,
      //   B4: 1,
      //   B3: 1,
      //   C4: 1,
      //   OJ: 1,
      //   A1: 1,
      //   B9: 1,
      //   A4: 1,
      //   P1A: 1,
      //   C2A: 1,
      //   C2B: 1,
      //   FP: 1,
      //   PI: 1,
      //   P: 1,
      //   FC: 1,
      //   GU: 1,
      //   GS: 1,
      //   PG: 1,
      //   C1A: 1,
      //   C1B: 1,
      //   KK: 1,
      //   B1: 1,
      //   W1: 1,
      //   W2: 1,
      // },
      permission :{"B19":1},
      iconClass: "fa fa-dashboard",
    },
  },

  {
    route: "products-textile",
    name: "products-textile",
    moduleId: PLATFORM.moduleName('./modules/master/product-textile/index', 'master'),
    nav: true,
    title: "Barang Jadi Dyeing Printing",
    auth: true,
    settings: {
      group: "master",
      // permission: { C5: 1, C9: 1 },
      permission :{"B56":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "product-textiles/all",
    name: "product-textiles/all",
    moduleId: PLATFORM.moduleName('./modules/master/product-textile-all/index', 'master'),
    nav: true,
    title: "Barang Jadi Dyeing Printing (All User)",
    auth: true,
    settings: {
      group: "master",
      // permission: { C5: 1, C9: 1 },
      permission: {"B57": 1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "products/non-purchasing",
    name: "products/non-purchasing",
    moduleId: PLATFORM.moduleName('./modules/master/product-non-purchasing/index', 'master'),
    nav: true,
    title: "Barang Non Pembelian",
    auth: true,
    settings: {
      group: "master",
      // permission: { 
      //    C9: 1,
      //   F4: 1,
      //   F2: 1,
      //   A2: 1,
      //   A1: 1,
      //   S1: 1,
      //   S2: 1,
      //   S3: 1,
      //   S4: 1,
      //   SP3: 1,
      //   W2: 1
      //   },
      permission :{"B20":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "income-taxes",
    name: "income-taxes",
    moduleId: PLATFORM.moduleName('./modules/master/income-tax/index', 'master'),
    nav: true,
    title: "Pajak PPH",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B21":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "budgets",
    name: "budgets",
    moduleId: PLATFORM.moduleName('./modules/master/budget/index', 'master'),
    nav: true,
    title: "Budget",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 },
      permission :{"B22":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "currencies",
    name: "currencies",
    moduleId: PLATFORM.moduleName('./modules/master/currency/index', 'master'),
    nav: true,
    title: "Mata Uang Tekstil",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B23":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "divisions",
    name: "divisions",
    moduleId: PLATFORM.moduleName('./modules/master/division/index', 'master'),
    nav: true,
    title: "Divisi",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 ,B1: 1, B12: 1},
      permission :{"B24":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "categories",
    name: "categories",
    moduleId: PLATFORM.moduleName('./modules/master/category/index', 'master'),
    nav: true,
    title: "Kategori",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B25":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "accounting-categories",
    name: "accounting-categories",
    moduleId: PLATFORM.moduleName('./modules/master/accounting-category/index', 'master'),
    nav: true,
    title: "Kategori Pembukuan",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B26":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "budget-categories",
    name: "budget-categories",
    moduleId: PLATFORM.moduleName('./modules/master/budget-category/index', 'master'),
    nav: true,
    title: "Kategori Anggaran",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B27":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "units",
    name: "units",
    moduleId: PLATFORM.moduleName('./modules/master/unit/index', 'master'),
    nav: true,
    title: "Unit",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B28":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "accounting-units",
    name: "accounting-units",
    moduleId: PLATFORM.moduleName('./modules/master/accounting-unit/index', 'master'),
    nav: true,
    title: "Unit Pembukuan",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, B1: 1, B12: 1 },
      permission :{"B29":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "machine-types",
    name: "machine-types",
    moduleId: PLATFORM.moduleName('./modules/master/machine-type/index', 'master'),
    nav: true,
    title: "Jenis Mesin",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 },
      permission :{"B30":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "machines",
    name: "machines",
    moduleId: PLATFORM.moduleName('./modules/master/machine/index', 'master'),
    nav: true,
    title: "Mesin",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, F1: 1, F2: 1 },
      permission :{"B31":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "instruksi",
    name: "instruksi",
    moduleId: PLATFORM.moduleName('./modules/master/instruksi/index', 'master'),
    nav: true,
    title: "Instruksi",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, F1: 1, F2: 1 },
      permission :{"B32":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "step",
    name: "step",
    moduleId: PLATFORM.moduleName('./modules/master/step/index', 'master'),
    nav: true,
    title: "Step",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, F1: 1, F2: 1 },
      permission :{"B33":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "companies",
    name: "companies",
    moduleId: PLATFORM.moduleName('./modules/master/company/index', 'master'),
    nav: true,
    title: "Perusahaan",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A1: 1, A2: 1, PGA: 1, PA: 1, PM: 1, PE: 1 },
      permission :{"B34":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "contacts",
    name: "contacts",
    moduleId: PLATFORM.moduleName('./modules/master/contact/index', 'master'),
    nav: true,
    title: "Kontak",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A1: 1, A2: 1, PGA: 1, PA: 1, PM: 1, PE: 1 },
      permission :{"B35":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "duration-estimations",
    name: "duration-estimations",
    moduleId: PLATFORM.moduleName('./modules/master/fp-duration-estimation/index', 'master'),
    nav: true,
    title: "Estimasi Durasi Produksi",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1, A1: 1, A2: 1 },
      permission :{"B36":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "bad-output-reasons",
    name: "bad-output-reasons",
    moduleId: PLATFORM.moduleName('./modules/master/bad-output-reason/index', 'master'),
    nav: true,
    title: "Keterangan Bad Output",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 },
      permission :{"B37":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "deal-tracking-reasons",
    name: "deal-tracking-reasons",
    moduleId: PLATFORM.moduleName('./modules/master/deal-tracking-reason/index', 'master'),
    nav: true,
    title: "Alasan Deal Tracking",
    auth: true,
    settings: {
      group: "master",
      // permission: { C9: 1 },
      permission :{"B38":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "/garment/garment-currency",
    name: "kurs-currency",
    moduleId: PLATFORM.moduleName('./modules/garment-purchasing/garment-currency/index', 'master'),
    nav: true,
    title: "Mata Uang Garment",
    auth: true,
    settings: {
      group: "master",
      // permission: { P1: 1, P3: 1, P4: 1, P6: 1, P7: 1, PG: 1, C9: 1, B1: 1, B12: 1 },
      permission :{"B39":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "budget-currency",
    name: "budget-currency",
    moduleId: PLATFORM.moduleName('./modules/master/budget-currency/index', 'master'),
    nav: true,
    title: "Kurs Budget",
    auth: true,
    settings: {
      group: "master",
      // permission: { P1: 1, P3: 1, P4: 1, P6: 1, P7: 1, PG: 1, C9: 1 },
      permission :{"B40":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "storage",
    name: "storage",
    moduleId: PLATFORM.moduleName('./modules/master/storage/index', 'master'),
    nav: true,
    title: "Storage",
    auth: true,
    settings: {
      group: "master",
      // permission: { P1: 1, P3: 1, P4: 1, P6: 1, P7: 1, PG: 1, C9: 1 },
      permission :{"B41":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "holiday",
    name: "holiday",
    moduleId: PLATFORM.moduleName('./modules/master/holiday-budgeting/index', 'master'),
    nav: true,
    title: "Hari Libur",
    auth: true,
    settings: {
      group: "master",
      //permission: { "C9": 1 },
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "spinning-production-lot",
    name: "spinning-production-lot",
    moduleId: PLATFORM.moduleName('./modules/master/spinning-production-lot/index', 'master'),
    nav: true,
    title: "Nomor Lot Produksi",
    auth: true,
    settings: {
      group: "master",
      //permission: { "*": 1 },
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "spinning-yarn",
    name: "spinning-yarn",
    moduleId: PLATFORM.moduleName('./modules/master/spinning-yarn/index', 'master'),
    nav: true,
    title: "Benang Spinning",
    auth: true,
    settings: {
      group: "master",
      //permission: { "*": 1 },
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "yarn-material",
    name: "yarn-material",
    moduleId: PLATFORM.moduleName('./modules/master/yarn-material/index', 'master'),
    nav: true,
    title: "Nomor Benang Material",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B42":1},
      iconClass: "fa fa-dashboard",
    },
  },

  {
    route: "material-construction",
    name: "material-construction",
    moduleId: PLATFORM.moduleName('./modules/master/material-construction/index', 'master'),
    nav: true,
    title: "Konstruksi Material",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B43":1},
      iconClass: "fa fa-dashboard",
    },
  },

  {
    route: "term-of-payment",
    name: "term-of-payment",
    moduleId: PLATFORM.moduleName('./modules/master/term-of-payment/index', 'master'),
    nav: true,
    title: "Term of Payment",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 ,B1: 1, B12: 1},
      permission :{"B44":1},
      iconClass: "fa fa-dashboard",
    },
  },

  {
    route: "comodity",
    name: "comodity",
    moduleId: PLATFORM.moduleName('./modules/master/comodity/index', 'master'),
    nav: true,
    title: "Komoditas",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B45":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "design-motives",
    name: "design-motives",
    moduleId: PLATFORM.moduleName('./modules/master/design-motives/index', 'master'),
    nav: true,
    title: "Desain Motif",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B46":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "order-type",
    name: "order-type",
    moduleId: PLATFORM.moduleName('./modules/master/order-type/index', 'master'),
    nav: true,
    title: "Jenis Order",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B47":1},
      iconClass: "fa fa-dashboard",
    },
  },

  {
    route: "process-type",
    name: "process-type",
    moduleId: PLATFORM.moduleName('./modules/master/process-type/index', 'master'),
    nav: true,
    title: "Jenis Proses",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B48":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "product-type",
    name: "product-type",
    moduleId: PLATFORM.moduleName('./modules/master/product-type/index', 'master'),
    nav: true,
    title: "Jenis Produk",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B49":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "line",
    name: "line",
    moduleId: PLATFORM.moduleName('./modules/master/line/index', 'master'),
    nav: true,
    title: "Line",
    auth: true,
    settings: {
      group: "master",
      //permission: { "C9": 1 },
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "rate",
    name: "rate",
    moduleId: PLATFORM.moduleName('./modules/master/rate/index', 'master'),
    nav: true,
    title: "Rate",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B50":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "size",
    name: "size",
    moduleId: PLATFORM.moduleName('./modules/master/size/index', 'master'),
    nav: true,
    title: "Size",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B51":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "size-range",
    name: "size-range",
    moduleId: PLATFORM.moduleName('./modules/master/size-range/index', 'master'),
    nav: true,
    title: "Size Range",
    auth: true,
    settings: {
      group: "master",
      //permission: { "*": 1 },
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "efficiency",
    name: "efficiency",
    moduleId: PLATFORM.moduleName('./modules/master/efficiency/index', 'master'),
    nav: true,
    title: "Efficiency",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B52":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "machine-spinning",
    name: "machine-spinning",
    moduleId: PLATFORM.moduleName('./modules/master/machine-spinning/index', 'master'),
    nav: true,
    title: "Mesin Spinning",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B53":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "bank-cash-receipt-type",
    name: "bank-cash-receipt-type",
    moduleId: PLATFORM.moduleName('./modules/master/bank-cash-receipt-type/index', 'master'),
    nav: true,
    title: "Jenis Penerimaan Kas Bank",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B54":1},
      iconClass: "fa fa-dashboard",
    },
  },
  {
    route: "vat",
    name: "vat",
    moduleId: PLATFORM.moduleName('./modules/master/vat/index', 'master'),
    nav: true,
    title: "Pajak PPN",
    auth: true,
    settings: {
      group: "master",
      // permission: { "*": 1 },
      permission :{"B55":1},
      iconClass: "fa fa-dashboard",
    },
  },

  
];
